### ISSUE TITLE
The script doesn't work

### ISSUE THREAD

**Issue by Talebano** [behdadahmadi/instamaker#1]
The script seems to have been written in an oldest version of python..or the code is simply wrong.
For istance,command Print needs parenthesis,and in instamaker.py all print commands are written without!Then,I think there's something wrong with the parser and probably also with the strings.
I don't know if the script will work,but surely there are many syntax errors.Maybe without these errors this script will effectively create accounts,I don't know...

**Comment by behdadahmadi** [comment]
The script worked well,but now security and API of Instagram has been changed,and the script no longer work. I check the syntax and it has not any problem within. `print` command DOES NOT NEED parenthesis. `print` command works with or without parenthesis. This script is written in Python 2.7,maybe you use Python 3.x to run this script.

**Comment by Talebano** [comment]
Sorry man,I'm a newbie in python and I didn't think that there were these
differences between python 2 and python 3.
Anyway,could you be interested in writing a similar script for me?
I can pay you

2017-06-21 17:59 GMT+02:00 Behdad Ahmadi <notifications@github.com>:

**Comment by behdadahmadi** [comment]
No problem man,but I am so sorry, I can't help you due to new security and API of Instagram. They change it to make it more secure. Anyway you need a proxy(sniffing) between your phone and Instagram server to intercept traffic(header,data) to know their mechanism(algorithm or etc) to write new script. I really don't have time to make it done,sorry.

**Comment by Talebano** [comment]
Thank you,really man :)
good luck in everything

2017-06-25 21:29 GMT+02:00 Behdad Ahmadi <notifications@github.com>:

**Comment by behdadahmadi** [comment]
You're welcome :-) 
Thanks a lot. You too.
